# Introduction to Numpy

In [36]:
import numpy as np

# Creating Arrays
print("-----------Creating Arrays---------")
print(f"Using np.array: {np.array([1, 2, 3])}")
print(f"Initiating using np.zeros: {np.zeros((2, 3))}")
print(f"Using np.ones: {np.ones(5)}")
print(f"Initiating an identity matrix: {np.eye(3)}")
print(f"Using np.arange: {np.arange(0, 10, 2)}")
print(f"Using np.linsapce: {np.linspace(0, 2, 5)}")

# Array Attributes
print("-----------Array Attributes---------")
x = np.array([[1, 2], [3, 4]])
print(x.shape)
print(x.ndim)
print(x.dtype)

# Vectorized Operations
print("-----------Vectorized Operations---------")
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)
print(x * y)
print(x ** 2)

# Broadcasting
print("-----------Broadcasting---------")
x = np.array([[1], [2], [3]])
y = np.array([10, 20, 30])
print(x + y)

# Indexing and Slicing
print("-----------Indexing and Slicing---------")
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x[0, 1])
print(x[:, 1])
print(x[1, :])

# Boolean Indexing
print("-----------Boolean Indexing---------")
x = np.array([1, 2, 3, 4, 5])
print(x[x > 2])

# Aggregations
print("-----------Aggregations---------")
x = np.array([[1, 2], [3, 4]])
print(x.sum())
print(x.mean())
print(x.max(axis=0))

# Linear Algebra
print("-----------Linear Algebra---------")
x = np.array([[1, 2], [3, 4]])
y = np.linalg.inv(x)
print(y)
print(np.dot(x, y))

# Random Numbers
print("-----------Random Numbers---------")
np.random.seed(0)
print(np.random.rand(3))
print(np.random.randn(2, 2))
print(np.random.randint(0, 10, size=5))

-----------Creating Arrays---------
Using np.array: [1 2 3]
Initiating using np.zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Using np.ones: [1. 1. 1. 1. 1.]
Initiating an identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Using np.arange: [0 2 4 6 8]
Using np.linsapce: [0.  0.5 1.  1.5 2. ]
-----------Array Attributes---------
(2, 2)
2
int32
-----------Vectorized Operations---------
[5 7 9]
[ 4 10 18]
[1 4 9]
-----------Broadcasting---------
[[11 21 31]
 [12 22 32]
 [13 23 33]]
-----------Indexing and Slicing---------
2
[2 5]
[4 5 6]
-----------Boolean Indexing---------
[3 4 5]
-----------Aggregations---------
10
2.5
[3 4]
-----------Linear Algebra---------
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
-----------Random Numbers---------
[0.5488135  0.71518937 0.60276338]
[[-2.2683282   1.33354538]
 [-0.84272405  1.96992445]]
[6 8 8 1 6]


In [ ]:
import numpy as np

print(np.__version__)
x = np.zeros(10)
print(x)


1.26.4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
