# Numpy exercises

In [16]:
# Import the numpy packges under the name np

import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

# Create a null vector of size 10
x = np.zeros(10)
print(x)

# How to find the memory size of any array
print(x.nbytes)


# How to get the documentation of the numpy add function from the command line?
!python -c "import numpy; help(numpy.add)"


1.26.4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc res

In [18]:
# Create a null vector of size 10 but the fifth value which is 1
x = np.zeros(10)
x[4] = 1
print(x)

# Create a vector with values ranging from 10 to 49
x = np.arange(10, 50)
print(x)

# Reverse a vector (first element becomes last)
x = np.arange(10, 50)
x = x[::-1]
print(x)

# Create a 3x3 matrix with values ranging from 0 to 8
x = np.arange(9).reshape(3, 3)
print(x)

# Find indices of non-zero elements from [1,2,0,0,4,0]
x = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(x)
print(indices)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(array([0, 1, 4], dtype=int64),)


In [19]:
# Create a 3x3 identity matrix
x = np.eye(3)
print(x)

# Create a 3x3x3 array with random values
x = np.random.random((3, 3, 3))
print(x)

# Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.random((10, 10))
min_val = np.min(x)
max_val = np.max(x)
print("Min:", min_val)
print("Max:", max_val)

# Create a random vector of size 30 and find the mean value
x = np.random.random(30)
mean_val = np.mean(x)
print("Mean:", mean_val)

# Create a 2D array with 1 on the border and 0 inside
x = np.ones((5, 5))
x[1:-1, 1:-1] = 0
print(x)

# How to add a border (filled with 0's) around an existing array?
x = np.array([[1, 2], [3, 4]])
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[[0.95303957 0.30164302 0.45371491]
  [0.67325603 0.53774625 0.38000168]
  [0.34464972 0.42438977 0.1229501 ]]

 [[0.7614439  0.43901449 0.1849518 ]
  [0.26038956 0.0241983  0.95646483]
  [0.05521932 0.97066347 0.29732064]]

 [[0.28722885 0.60697827 0.35591739]
  [0.03911087 0.75370926 0.68719423]
  [0.45520625 0.07996393 0.54856901]]]
Min: 0.006789283521195011
Max: 0.9880782083763425
Mean: 0.4430778989580165
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


In [20]:
# What is the result of the following expression?
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1

# The results of the expressions are:
print(0 * np.nan)  # nan
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
x = np.zeros((5, 5))
x[np.arange(1, 5), np.arange(0, 4)] = 1
print(x)

# Create a 8x8 matrix and fill it with a checkerboard pattern
x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

# Consider a (6,7,8) shape array, how to get the index of the 100th element?
x = np.zeros((6, 7, 8))
index_100 = np.unravel_index(99, x.shape)  # 99 because index starts from 0
print(index_100)

nan
False
False
nan
True
False
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
(1, 5, 3)


In [21]:
# Create a checkerboard 8x8 matrix using the tile function
x = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(x)

# Normalize a 5x5 random matrix
x = np.random.random((5, 5))
x_min = x.min()
x_max = x.max()
x_normalized = (x - x_min) / (x_max - x_min)
print(x_normalized)

# Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color_dtype = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])
print(color_dtype)

# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
x1 = np.random.random((5, 3))
x2 = np.random.random((3, 2))
result = np.dot(x1, x2)
print(result)

# Given a 1D array, negate all elements which are between 3 and 8, in place.
x = np.arange(10)
x[(x > 3) & (x < 8)] *= -1
print(x)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0.00228197 0.94968887 0.89527675 0.02973853 0.22275169]
 [0.25900667 0.46138989 0.57099047 0.51134774 0.87171967]
 [1.         0.19243852 0.82597543 0.99598063 0.09764503]
 [0.49211662 0.98328666 0.         0.380012   0.08702584]
 [0.52898435 0.36917148 0.15344925 0.95765466 0.92612796]]
[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
[[0.66962129 1.04809677]
 [0.49371099 1.07643219]
 [0.66280744 0.69689288]
 [0.66659852 1.19994108]
 [0.36549324 0.86530276]]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [ ]:
#  How to get the dates of yesterday, today and tomorrow?

from datetime import datetime, timedelta
# Get today's date
today = datetime.now()
# Get yesterday's date
yesterday = today - timedelta(days=1)
# Get tomorrow's date
tomorrow = today + timedelta(days=1)
print("Yesterday:", yesterday.strftime('%Y-%m-%d'))
print("Today:", today.strftime('%Y-%m-%d'))
print("Tomorrow:", tomorrow.strftime('%Y-%m-%d'))

Yesterday: 2025-06-05
Today: 2025-06-06
Tomorrow: 2025-06-07
